// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceProxyMessage.proto

package com.dapp.server.protobuf;

public final class DeviceProxyMessageProto {
  private DeviceProxyMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceProxyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dapp.server.protobuf.DeviceProxyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_name = 1;</code>
     * @return The userName.
     */
    String getUserName();
    /**
     * <code>string user_name = 1;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int32 result = 3;</code>
     * @return The result.
     */
    int getResult();

    /**
     * <code>int32 code = 4;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>int32 error = 6;</code>
     * @return The error.
     */
    int getError();

    /**
     * <code>string dst = 7;</code>
     * @return The dst.
     */
    String getDst();
    /**
     * <code>string dst = 7;</code>
     * @return The bytes for dst.
     */
    com.google.protobuf.ByteString
        getDstBytes();

    /**
     * <code>int32 port = 8;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>int32 tag = 9;</code>
     * @return The tag.
     */
    int getTag();
  }
  /**
   * Protobuf type {@code com.dapp.server.protobuf.DeviceProxyMessage}
   */
  public static final class DeviceProxyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dapp.server.protobuf.DeviceProxyMessage)
      DeviceProxyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceProxyMessage.newBuilder() to construct.
    private DeviceProxyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceProxyMessage() {
      userName_ = "";
      id_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      dst_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeviceProxyMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceProxyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 24: {

              result_ = input.readInt32();
              break;
            }
            case 32: {

              code_ = input.readInt32();
              break;
            }
            case 42: {

              data_ = input.readBytes();
              break;
            }
            case 48: {

              error_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              dst_ = s;
              break;
            }
            case 64: {

              port_ = input.readInt32();
              break;
            }
            case 72: {

              tag_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DeviceProxyMessageProto.internal_static_com_dapp_server_protobuf_DeviceProxyMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DeviceProxyMessageProto.internal_static_com_dapp_server_protobuf_DeviceProxyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeviceProxyMessage.class, Builder.class);
    }

    public static final int USER_NAME_FIELD_NUMBER = 1;
    private volatile Object userName_;
    /**
     * <code>string user_name = 1;</code>
     * @return The userName.
     */
    @Override
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string user_name = 1;</code>
     * @return The bytes for userName.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile Object id_;
    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    @Override
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private int result_;
    /**
     * <code>int32 result = 3;</code>
     * @return The result.
     */
    @Override
    public int getResult() {
      return result_;
    }

    public static final int CODE_FIELD_NUMBER = 4;
    private int code_;
    /**
     * <code>int32 code = 4;</code>
     * @return The code.
     */
    @Override
    public int getCode() {
      return code_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int ERROR_FIELD_NUMBER = 6;
    private int error_;
    /**
     * <code>int32 error = 6;</code>
     * @return The error.
     */
    @Override
    public int getError() {
      return error_;
    }

    public static final int DST_FIELD_NUMBER = 7;
    private volatile Object dst_;
    /**
     * <code>string dst = 7;</code>
     * @return The dst.
     */
    @Override
    public String getDst() {
      Object ref = dst_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dst_ = s;
        return s;
      }
    }
    /**
     * <code>string dst = 7;</code>
     * @return The bytes for dst.
     */
    @Override
    public com.google.protobuf.ByteString
        getDstBytes() {
      Object ref = dst_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dst_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 8;
    private int port_;
    /**
     * <code>int32 port = 8;</code>
     * @return The port.
     */
    @Override
    public int getPort() {
      return port_;
    }

    public static final int TAG_FIELD_NUMBER = 9;
    private int tag_;
    /**
     * <code>int32 tag = 9;</code>
     * @return The tag.
     */
    @Override
    public int getTag() {
      return tag_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (result_ != 0) {
        output.writeInt32(3, result_);
      }
      if (code_ != 0) {
        output.writeInt32(4, code_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      if (error_ != 0) {
        output.writeInt32(6, error_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dst_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, dst_);
      }
      if (port_ != 0) {
        output.writeInt32(8, port_);
      }
      if (tag_ != 0) {
        output.writeInt32(9, tag_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, result_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, code_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      if (error_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, error_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dst_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, dst_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, port_);
      }
      if (tag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, tag_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DeviceProxyMessage)) {
        return super.equals(obj);
      }
      DeviceProxyMessage other = (DeviceProxyMessage) obj;

      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (getResult()
          != other.getResult()) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getError()
          != other.getError()) return false;
      if (!getDst()
          .equals(other.getDst())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (getTag()
          != other.getTag()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError();
      hash = (37 * hash) + DST_FIELD_NUMBER;
      hash = (53 * hash) + getDst().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTag();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DeviceProxyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceProxyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceProxyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceProxyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceProxyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceProxyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceProxyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DeviceProxyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DeviceProxyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DeviceProxyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DeviceProxyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DeviceProxyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DeviceProxyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dapp.server.protobuf.DeviceProxyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dapp.server.protobuf.DeviceProxyMessage)
        DeviceProxyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeviceProxyMessageProto.internal_static_com_dapp_server_protobuf_DeviceProxyMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeviceProxyMessageProto.internal_static_com_dapp_server_protobuf_DeviceProxyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeviceProxyMessage.class, Builder.class);
      }

      // Construct using com.dapp.server.protobuf.DeviceProxyMessageProto.DeviceProxyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        userName_ = "";

        id_ = "";

        result_ = 0;

        code_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        error_ = 0;

        dst_ = "";

        port_ = 0;

        tag_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DeviceProxyMessageProto.internal_static_com_dapp_server_protobuf_DeviceProxyMessage_descriptor;
      }

      @Override
      public DeviceProxyMessage getDefaultInstanceForType() {
        return DeviceProxyMessage.getDefaultInstance();
      }

      @Override
      public DeviceProxyMessage build() {
        DeviceProxyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DeviceProxyMessage buildPartial() {
        DeviceProxyMessage result = new DeviceProxyMessage(this);
        result.userName_ = userName_;
        result.id_ = id_;
        result.result_ = result_;
        result.code_ = code_;
        result.data_ = data_;
        result.error_ = error_;
        result.dst_ = dst_;
        result.port_ = port_;
        result.tag_ = tag_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DeviceProxyMessage) {
          return mergeFrom((DeviceProxyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DeviceProxyMessage other) {
        if (other == DeviceProxyMessage.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getError() != 0) {
          setError(other.getError());
        }
        if (!other.getDst().isEmpty()) {
          dst_ = other.dst_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getTag() != 0) {
          setTag(other.getTag());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DeviceProxyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DeviceProxyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object userName_ = "";
      /**
       * <code>string user_name = 1;</code>
       * @return The userName.
       */
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string user_name = 1;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_name = 1;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 1;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 2;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>int32 result = 3;</code>
       * @return The result.
       */
      @Override
      public int getResult() {
        return result_;
      }
      /**
       * <code>int32 result = 3;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 4;</code>
       * @return The code.
       */
      @Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 4;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 5;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int error_ ;
      /**
       * <code>int32 error = 6;</code>
       * @return The error.
       */
      @Override
      public int getError() {
        return error_;
      }
      /**
       * <code>int32 error = 6;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(int value) {
        
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 error = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        
        error_ = 0;
        onChanged();
        return this;
      }

      private Object dst_ = "";
      /**
       * <code>string dst = 7;</code>
       * @return The dst.
       */
      public String getDst() {
        Object ref = dst_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dst_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string dst = 7;</code>
       * @return The bytes for dst.
       */
      public com.google.protobuf.ByteString
          getDstBytes() {
        Object ref = dst_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dst_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dst = 7;</code>
       * @param value The dst to set.
       * @return This builder for chaining.
       */
      public Builder setDst(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dst = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDst() {
        
        dst_ = getDefaultInstance().getDst();
        onChanged();
        return this;
      }
      /**
       * <code>string dst = 7;</code>
       * @param value The bytes for dst to set.
       * @return This builder for chaining.
       */
      public Builder setDstBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dst_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 8;</code>
       * @return The port.
       */
      @Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 8;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int tag_ ;
      /**
       * <code>int32 tag = 9;</code>
       * @return The tag.
       */
      @Override
      public int getTag() {
        return tag_;
      }
      /**
       * <code>int32 tag = 9;</code>
       * @param value The tag to set.
       * @return This builder for chaining.
       */
      public Builder setTag(int value) {
        
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 tag = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTag() {
        
        tag_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dapp.server.protobuf.DeviceProxyMessage)
    }

    // @@protoc_insertion_point(class_scope:com.dapp.server.protobuf.DeviceProxyMessage)
    private static final DeviceProxyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DeviceProxyMessage();
    }

    public static DeviceProxyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceProxyMessage>
        PARSER = new com.google.protobuf.AbstractParser<DeviceProxyMessage>() {
      @Override
      public DeviceProxyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceProxyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceProxyMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DeviceProxyMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public DeviceProxyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dapp_server_protobuf_DeviceProxyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dapp_server_protobuf_DeviceProxyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030DeviceProxyMessage.proto\022\030com.dapp.ser" +
      "ver.protobuf\"\226\001\n\022DeviceProxyMessage\022\021\n\tu" +
      "ser_name\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\016\n\006result\030\003 \001" +
      "(\005\022\014\n\004code\030\004 \001(\005\022\014\n\004data\030\005 \001(\014\022\r\n\005error\030" +
      "\006 \001(\005\022\013\n\003dst\030\007 \001(\t\022\014\n\004port\030\010 \001(\005\022\013\n\003tag\030" +
      "\t \001(\005B3\n\030com.dapp.server.protobufB\027Devic" +
      "eProxyMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dapp_server_protobuf_DeviceProxyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dapp_server_protobuf_DeviceProxyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dapp_server_protobuf_DeviceProxyMessage_descriptor,
        new String[] { "UserName", "Id", "Result", "Code", "Data", "Error", "Dst", "Port", "Tag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
